/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.administradorbanda.views;

import br.com.administradorbanda.banco.BancoDeDados;
import br.com.administradorbanda.utilitarios.JanelaUtils;
import br.com.administradorbanda.dao.MusicasDAO;
import br.com.administradorbanda.models.MusicasModel;
import br.com.administradorbanda.views.MenuView;
import br.com.administradorbanda.views.EditarCadastrarMusicaView;
import java.sql.Connection;

/**
 *
 * @author elder
 */
public class MusicasView extends javax.swing.JFrame {
    Connection conexaoBanco = BancoDeDados.getConnection();
    MusicasDAO musicasDao = new MusicasDAO(conexaoBanco);
    MusicasModel model = new MusicasModel(musicasDao);

    /**
     * Creates new form MusicasView
     */
    public MusicasView() {
        initComponents();
        
        tabelaListarMusicas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarMusicas = new javax.swing.JTable();
        btnEditarCadastrarMusica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarMusica = new javax.swing.JTextField();
        btnVoltarMusicasView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Musicas");

        tabelaListarMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaListarMusicas);

        btnEditarCadastrarMusica.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnEditarCadastrarMusica.setText("Editar/Cadastrar");
        btnEditarCadastrarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadastrarMusicaActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        txtBuscarMusica.setToolTipText("Busca por nome da musica");
        txtBuscarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarMusicaActionPerformed(evt);
            }
        });
        txtBuscarMusica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarMusicaKeyPressed(evt);
            }
        });

        btnVoltarMusicasView.setText("<");
        btnVoltarMusicasView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMusicasViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltarMusicasView)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarCadastrarMusica))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnEditarCadastrarMusica)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltarMusicasView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCadastrarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadastrarMusicaActionPerformed
        EditarCadastrarMusicaView editarCadastrarMusicaView = new EditarCadastrarMusicaView();
        this.dispose();
        JanelaUtils.centralizar(editarCadastrarMusicaView);
        editarCadastrarMusicaView.setVisible(true);
    }//GEN-LAST:event_btnEditarCadastrarMusicaActionPerformed

    private void btnVoltarMusicasViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMusicasViewActionPerformed
        MenuView menuView = new MenuView();
        this.dispose();
        JanelaUtils.centralizar(menuView);
        menuView.setVisible(true);
    }//GEN-LAST:event_btnVoltarMusicasViewActionPerformed

    private void txtBuscarMusicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMusicaKeyPressed
        String buscarMusicaValor = txtBuscarMusica.getText();
        if(buscarMusicaValor.length() == 0){
            model.buscarMusicas();
        }
        if(buscarMusicaValor.length() >= 3) {
            model.buscarMusicaPorTitulo(buscarMusicaValor);
        }
    }//GEN-LAST:event_txtBuscarMusicaKeyPressed

    private void txtBuscarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarMusicaActionPerformed

    }//GEN-LAST:event_txtBuscarMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MusicasView musicasView = new MusicasView();
                JanelaUtils.centralizar(musicasView);
                musicasView.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCadastrarMusica;
    private javax.swing.JButton btnVoltarMusicasView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListarMusicas;
    private javax.swing.JTextField txtBuscarMusica;
    // End of variables declaration//GEN-END:variables
}
